# Generated by Django 4.0.1 on 2022-01-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
